spring:
  datasource:
    password: srivatsan
    url: jdbc:mysql://localhost:3306/test
    username: root
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
  config:
    activate:
      on-profile:
      - dev

---

spring:
  datasource:
    password: 
    url: jdbc:h2:file:C:/h2data/sample
    username: sa
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
   
  config:
    activate:
      on-profile:
      - test
      
      
