
package com.training.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ImageProcessing", targetNamespace = "http://ifaces.training.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ImageProcessing {


    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getImage", targetNamespace = "http://ifaces.training.com/", className = "com.training.client.GetImage")
    @ResponseWrapper(localName = "getImageResponse", targetNamespace = "http://ifaces.training.com/", className = "com.training.client.GetImageResponse")
    @Action(input = "http://ifaces.training.com/ImageProcessing/getImageRequest", output = "http://ifaces.training.com/ImageProcessing/getImageResponse")
    public byte[] getImage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendImage", targetNamespace = "http://ifaces.training.com/", className = "com.training.client.SendImage")
    @ResponseWrapper(localName = "sendImageResponse", targetNamespace = "http://ifaces.training.com/", className = "com.training.client.SendImageResponse")
    @Action(input = "http://ifaces.training.com/ImageProcessing/sendImageRequest", output = "http://ifaces.training.com/ImageProcessing/sendImageResponse")
    public String sendImage(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0);

}
